"""adding name column in batches table

Revision ID: 2997219269fd
Revises: 16f425efe807
Create Date: 2025-08-11 23:42:22.192364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2997219269fd'
down_revision = '16f425efe807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'name')
    # ### end Alembic commands ###
