"""adding mentor_name column in batches table

Revision ID: 49f574732fdb
Revises: 5c3f13f5b93b
Create Date: 2025-05-03 16:02:54.485842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f574732fdb'
down_revision = '5c3f13f5b93b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('mentor_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'mentor_name')
    # ### end Alembic commands ###
