"""adding users table

Revision ID: c8c07cde4ba6
Revises: 
Create Date: 2025-08-07 12:30:04.904684

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

from app.utils.enums import GenderTypes, Roles
from app.utils.hasher import Hasher


# revision identifiers, used by Alembic.
revision = 'c8c07cde4ba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    
    conn = op.get_bind()
    # Insert a default user
    conn.execute(
            text("""
                INSERT INTO users (
                    name, email, gender, password, phone_number, role, created_at, created_by, updated_at, 
                    updated_by, is_active
                )
                VALUES (
                    :name, :email, :gender, :password, :phone_number, :role, :created_at, :created_by, 
                    :updated_at, :updated_by, :is_active
                )
            """),
        {
            "name": 'Siva Teja',
            "email": 'vantasivateja@gmail.com',
            "gender": GenderTypes.MALE,
            "password": Hasher.get_password_hash("String@123"),
            "phone_number": '1234567890',
            "role": Roles.ADMIN.value,
            "created_at": datetime.utcnow(),
            "created_by": None,
            "updated_at": datetime.utcnow(),
            "updated_by": None,
            "is_active": True
        }
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
