"""adding batch_student_payments table

Revision ID: e6879a975418
Revises: a0aeeaa559a3
Create Date: 2025-08-10 23:46:16.389045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6879a975418'
down_revision = 'a0aeeaa559a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_student_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_student_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('mentor_share', sa.Integer(), nullable=False),
    sa.Column('referral_share', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_student_id'], ['batch_students.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_student_payments')
    # ### end Alembic commands ###
