INVALID_SCHEMA = "INVALID_SCHEMA"
PUBLIC_SCHEMA = "public"
DB_NOT_UPTODATE = "DB_NOT_UPTODATE"
HEAD = "HEAD"
AUTHORIZATION = "Authorization"
INVALID_NOTIFICATION_TYPE = "INVALID_NOTIFICATION_TYPE"
TEMPLATE_FOLDER_NAME = "templates"
ATTACHMENT_FOLDER_NAME = "attachments"
TEMPLATE_FILE_EXTENTION = ".html.jinja"
USER_NOT_FOUND = "USER_NOT_FOUND"


#USER MANAGEMENT SERVICE RELATED CONSTANTS:
THE_USER_DETAILS_DOES_NOT_EXIST_FOR_THIS_ID = "THE_USER_DETAILS_DOES_NOT_EXIST_FOR_THIS_ID:"

# SYLLABUS SERVICE RELATED CONSTANTS:
SYLLABUS_CREATED_SUCCESSFULLY = "SYLLABUS_CREATED_SUCCESSFULLY"
SYLLABUS_UPDATED_SUCCESSFULLY = "SYLLABUS_UPDATED_SUCCESSFULLY"
SYLLABUS_DELETED_SUCCESSFULLY = "SYLLABUS_DELETED_SUCCESSFULLY"
SYLLABUS_NAME_ALREADY_EXISTS = "SYLLABUS_NAME_ALREADY_EXISTS"
SYLLABUS_NOT_FOUND = "SYLLABUS_NOT_FOUND"

# BATCH SERVICE RELATED CONSTANTS:
BATCH_CREATED_SUCCESSFULLY = "BATCH_CREATED_SUCCESSFULLY"
BATCH_UPDATED_SUCCESSFULLY = "BATCH_UPDATED_SUCCESSFULLY"
BATCH_DELETED_SUCCESSFULLY = "BATCH_DELETED_SUCCESSFULLY"
BATCH_NOT_FOUND = "BATCH_NOT_FOUND"

# STUDENT SERVICE RELATED CONSTANTS:
STUDENT_CREATED_SUCCESSFULLY = "STUDENT_CREATED_SUCCESSFULLY"
STUDENT_UPDATED_SUCCESSFULLY = "STUDENT_UPDATED_SUCCESSFULLY"
STUDENT_DELETED_SUCCESSFULLY = "STUDENT_DELETED_SUCCESSFULLY"
STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND"
STUDENT_EMAIL_ALREADY_EXISTS = "STUDENT_EMAIL_ALREADY_EXISTS"
STUDENT_BATCH_DETAILS_CREATED_SUCCESSFULLY = "STUDENT_BATCH_DETAILS_CREATED_SUCCESSFULLY"
STUDENT_BATCH_DETAILS_UPDATED_SUCCESSFULLY = "STUDENT_BATCH_DETAILS_UPDATED_SUCCESSFULLY"
STUDENT_BATCH_DETAILS_DELETED_SUCCESSFULLY = "STUDENT_BATCH_DETAILS_DELETED_SUCCESSFULLY"
MAPPING_NOT_FOUND = "MAPPING_NOT_FOUND"
STUDENT_ALREADY_EXISTS_IN_THE_BATCH = "STUDENT_ALREADY_EXISTS_IN_THE_BATCH"