name: Deploy to Mac mini

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rename docker-compose.prod.yml and start containers
        run: |
          mv docker-compose.prod.yml docker-compose.yml
          docker compose up -d
