name: Deploy to Mac mini

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname github-runner --ssh
 
      - name: Ping a Tailscale device
        run: |
          ping -c 4 100.76.154.55

      - name: Copy files to Mac mini
        uses: appleboy/scp-action@v0.1.6
        with:
          host: 100.76.154.55
          username: punit
          key: ${{ secrets.MACMINI_SSH_KEY }}
          source: "."
          target: "/Users/punit/www"
